server:
  port: 8701

spring:
  application:
    name: one-global
  datasource:
    druid:
      url: jdbc:mysql://leavemails.com:13306/one_global?useUnicode=true&useSSL=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: one
      password: 123!@#
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
