server:
  port: 8701

spring:
  application:
    name: one-global
  datasource:
    druid:
      url: jdbc:mysql://leavemails.com:13306/one_global?useUnicode=true&useSSL=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: one
      password: 123!@#
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: leavemails.com
    port: 16379
    password: qq282465134
    database: 1
    timeout: 5000
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
