server:
  port: 8701
spring:
  profiles:
    active: dev
  application:
    name: one-global
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
logging:
  config: classpath:config/logback-spring.xml