spring:
  datasource:
    druid:
      url: jdbc:mysql://mysql:3306/one_global?useUnicode=true&useSSL=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: one
      password: 123qwe
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis
    port: 6379
    password: qq282465134
    database: 1
    timeout: 5000
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000